import type { Metadata, Viewport } from "next"
import "src/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "",
  icons: [{ rel: "icon", url: "/favicon/favicon.ico" }],
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "rgb(130, 184, 172)" },
    { media: "(prefers-color-scheme: dark)", color: "rgb(22, 28, 36)" },
  ],
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
